export const SET_LOADER = "SET_LOADER"

export const INIT_MAIN_MENU = "INIT_MAIN_MENU"
export const HANDLE_STATE_MAIN_MENU = "HANDLE_STATE_MAIN_MENU"
export const GET_DATA_MAIN_MENU = "GET_DATA_MAIN_MENU"
export const GET_DATA_MAIN_MENU_SUCCESS = "GET_DATA_MAIN_MENU_SUCCESS"
